### ISSUE TITLE
Node for Newbs Crash Course

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-react#6]
@AntoineDao

As per our meetup, how about writing up a crash course for Node for inexperienced users?

As time goes on we can customize and streamline so it focuses primarily on what AEC peeps need to know in order to get started quickly. And I can add comments from a guinea-pig point of view.

Forked from https://github.com/ladybug-tools/spider-core/issues/4

**Comment by theo-armour** [comment]
@AntoineDao 

I have followed all the instructions here: https://github.com/ladybug-tools/spider-core/blob/master/tutorials/local-development.md. All seems good.

Now I am working on https://github.com/ladybug-tools/spider-core/blob/master/tutorials/getting-started.md

I have set things up two ways - editing index.js in spider-core and in a new folder - 

Using this index.js

```
const fs = require('fs');

const Spider = require('../spider-core');

const gbXMLString = fs.readFileSync('london-office.xml');

const gbXMLJson = Spider.gbXMLParser.parseFileXML(gbXMLString);

console.log(JSON.stringify(gbXMLJson, null, 2));
```
the following error is returned:

```
$ node index.js
[xmldom error]  element parse error: TypeError: source.charAt is not a function
@#[line:0,col:undefined]
D:\Dropbox\Public\git-repos\spider-core\node_modules\xmldom\sax.js:62
                        var xt = source.substring(start,end).replace(/&#?\w+;/g,entityReplacer);
                                        ^

TypeError: source.substring is not a function
    at appendText (D:\Dropbox\Public\git-repos\spider-core\node_modules\xmldom\sax.js:62:20)
    at parse (D:\Dropbox\Public\git-repos\spider-core\node_modules\xmldom\sax.js:199:4)
    at XMLReader.parse (D:\Dropbox\Public\git-repos\spider-core\node_modules\xmldom\sax.js:30:3)
    at DOMParser.parseFromString (D:\Dropbox\Public\git-repos\spider-core\node_modules\xmldom\dom-parser.js:26:7)
    at Object.parseFileXML (D:\Dropbox\Public\git-repos\spider-core\lib\gbXMLParser.js:65:24)
    at Object.<anonymous> (D:\Dropbox\Public\git-repos\spider-core\index.js:16:38)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)

 ```

The line that seems to fail is this one

    const Spider = require('../spider-core');

**Comment by AntoineDao** [comment]
It's probably because you haven't installed all the dependencies in your `spider-core` folder. 

```console
cd /path/to/spider-core
npm install
cd ../
node index.js
```
If this doesn't work then I would recommend sticking to the [example provided](http://www.ladybug.tools/spider-core/latest/tutorial-getting-started.html). I realise now that this example is missing a couple of commands for completeness so I'll add them here and then push them to docs when I've got time:

```console
mkdir my-cool-project
cd my-cool-project
npm init                           # Run through the npm init process of creating the packages
npm install --save @ladybug-tools/spider-core
```

And then write the code below in index.js:

```javascript
const fs = require('fs');
const Spider = require('@ladybug-tools/spider-core');

const gbXMLString = fs.readFileSync('/path/to/file.gbxml');

const gbXMLJson = Spider.gbXMLParser.parseFileXML(gbXMLString);

console.log(JSON.stringify(gbXMLJson, null, 2));
```

Also, on another note, I'd really recommend against writing your work in a Dropbox folder (especially if you've got sync turned on) as NodeJS projects can gather quite a few packages in the node_modules folder which will add a lot of unnecessary bandwidth usage to your network.

![image](https://user-images.githubusercontent.com/20436635/55461798-35d0d780-55ed-11e9-81e3-f6ad8f4048de.png)

**Comment by theo-armour** [comment]
@AntoineDao 

Still no luck. 

;-(

```
PS D:\node> cd spider-core-try3
PS D:\node\spider-core-try3> npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (spider-core-try3)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to D:\node\spider-core-try3\package.json:

{
  "name": "spider-core-try3",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes)
PS D:\node\spider-core-try3> dir


    Directory: D:\node\spider-core-try3


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         4/4/2019  12:55 AM            212 package.json


PS D:\node\spider-core-try3> npm install --save @ladybug-tools/spider-core
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN spider-core-try3@1.0.0 No description
npm WARN spider-core-try3@1.0.0 No repository field.

+ @ladybug-tools/spider-core@1.0.0
added 3 packages from 6 contributors and audited 3 packages in 5.476s
found 0 vulnerabilities

PS D:\node\spider-core-try3> node -v
v11.13.0
PS D:\node\spider-core-try3> node index.js
[xmldom error]  element parse error: TypeError: source.charAt is not a function
@#[line:0,col:undefined]
D:\node\spider-core-try3\node_modules\xmldom\sax.js:62
                        var xt = source.substring(start,end).replace(/&#?\w+;/g,entityReplacer);
                                        ^

TypeError: source.substring is not a function
    at appendText (D:\node\spider-core-try3\node_modules\xmldom\sax.js:62:20)
    at parse (D:\node\spider-core-try3\node_modules\xmldom\sax.js:199:4)
    at XMLReader.parse (D:\node\spider-core-try3\node_modules\xmldom\sax.js:30:3)
    at DOMParser.parseFromString (D:\node\spider-core-try3\node_modules\xmldom\dom-parser.js:26:7)
    at Object.parseFileXML (D:\node\spider-core-try3\node_modules\@ladybug-tools\spider-core\lib\gbXMLParser.js:58:24)
    at Object.<anonymous> (D:\node\spider-core-try3\index.js:6:38)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
PS D:\node\spider-core-try3>

```
index.js

```
const fs = require('fs');
const Spider = require('@ladybug-tools/spider-core');

const gbXMLString = fs.readFileSync('london-office.xml');

const gbXMLJson = Spider.gbXMLParser.parseFileXML(gbXMLString);

console.log(JSON.stringify(gbXMLJson, null, 2));

```

**Comment by AntoineDao** [comment]
Ha! My bad. It was because of the `readFileSync` function which was returning a Buffer rather than a string. Here is the corrected code:

```javascript
const fs = require('fs');
const Spider = require('@ladybug-tools/spider-core');

const gbXMLString = fs.readFileSync('london-office.xml');

const gbXMLJson = Spider.gbXMLParser.parseFileXML(gbXMLString.toString());

console.log(JSON.stringify(gbXMLJson, null, 2));
```

I'll update the docs just now.

**Comment by theo-armour** [comment]
@AntoineDao 

Bingo!

Yay we are in.

![image](https://user-images.githubusercontent.com/547626/55611019-1ba41000-5739-11e9-89a2-c689c3a99e8d.png)

**Comment by AntoineDao** [comment]
@theo-armour am I good to close this issue? We can re-open a new one for getting setup with spider-react?

**Comment by theo-armour** [comment]
@AntoineDao 

Yup, this issue is ok to close.
